/** أسماء عربية للصلاحيات تظهر في شاشة إدارة الأدوار. */
export const PERMISSION_LABELS: Record<string, string> = {
  'dashboard.view': 'عرض لوحة التحكم',
  'sales.view': 'عرض المبيعات',
  'sales.create': 'إنشاء فواتير بيع',
  'sales.payment': 'تحصيل دفعات الفواتير',
  'sales.void': 'إلغاء الفواتير',
  'sales.return': 'المرتجعات',
  'products.view': 'عرض المنتجات',
  'products.create': 'إضافة منتجات',
  'products.update': 'تعديل المنتجات والأسعار',
  'products.delete': 'حذف المنتجات',
  'products.manage': 'مراجعة/اعتماد المنتجات',
  'inventory.view': 'عرض المخزون',
  'inventory.adjust': 'تعديل كميات المخزون (جرد)',
  'inventory.transfer': 'نقل بضاعة بين المخازن',
  'categories.view': 'عرض التصنيفات',
  'categories.manage': 'إدارة التصنيفات',
  'brands.view': 'عرض الماركات',
  'brands.manage': 'إدارة الماركات',
  'customers.view': 'عرض العملاء',
  'customers.create': 'إضافة عملاء',
  'customers.update': 'تعديل العملاء',
  'customers.delete': 'حذف العملاء',
  'customers.payment': 'تحصيل من العملاء',
  'suppliers.view': 'عرض الموردين',
  'suppliers.create': 'إضافة موردين',
  'suppliers.update': 'تعديل الموردين',
  'suppliers.delete': 'حذف الموردين',
  'suppliers.settle': 'تسوية/سداد الموردين',
  'purchases.view': 'عرض المشتريات',
  'purchases.create': 'إنشاء فواتير شراء',
  'expenses.view': 'عرض المصروفات',
  'expenses.create': 'تسجيل مصروفات',
  'expenses.manage': 'إدارة فئات المصروفات',
  'cash_register.view': 'عرض الخزينة',
  'cash_register.manage': 'فتح/إغلاق الورديات',
  'branches.view': 'عرض الفروع',
  'branches.manage': 'إدارة الفروع',
  'warehouses.view': 'عرض المخازن',
  'warehouses.manage': 'إدارة المخازن',
  'reports.view': 'عرض التقارير',
  'reports.export': 'تصدير التقارير',
  'advanced_reports.view': 'التقارير المتقدمة',
  'branding.view': 'عرض الهوية البصرية',
  'branding.update': 'تعديل الهوية البصرية',
  'settings.view': 'عرض الإعدادات',
  'settings.update': 'تعديل الإعدادات',
  'users.view': 'عرض المستخدمين',
  'users.create': 'إضافة مستخدمين',
  'users.update': 'تعديل المستخدمين وكلمات مرورهم',
  'users.delete': 'حذف المستخدمين',
  'roles.manage': 'إدارة الأدوار والصلاحيات',
  'backup.export': 'تنزيل نسخة احتياطية',
  'api_keys.manage': 'إدارة مفاتيح API',
  'data.import': 'استيراد البيانات',
  'data.export': 'تصدير البيانات',
  'audit.view': 'عرض سجل النشاط',
};

export const PERMISSION_CATEGORY_LABELS: Record<string, string> = {
  dashboard: 'لوحة التحكم',
  sales: 'المبيعات',
  products: 'المنتجات',
  inventory: 'المخزون والفروع',
  customers: 'العملاء',
  suppliers: 'الموردين',
  purchases: 'المشتريات',
  expenses: 'المصروفات',
  cash_register: 'الخزينة',
  reports: 'التقارير',
  settings: 'الإعدادات',
  users: 'المستخدمين',
};
